version: '3'

services:
  test_db:
    image: postgres:10-alpine
    container_name: personal_finances_test_db
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
